name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Continuous Integration
      - name: Compile Project
        run: mvn clean compile

      # Continuous Testing
      - name: Run Tests
        run: mvn test

      # Continuous Deployment
      - name: Package Application
        run: mvn package

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: basic-java-maven
          path: target/*.jar