name: Publish Package

on:
push:
branches:
- main

jobs:
publish:

```
runs-on: ubuntu-latest

permissions:
  contents: read
  packages: write

steps:

  - name: Checkout Source
    uses: actions/checkout@v4

  - name: Setup Java
    uses: actions/setup-java@v4
    with:
      distribution: temurin
      java-version: 17
      server-id: github

  - name: Publish Package
    run: mvn deploy
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}